name = "bgapp-frontend"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./apps/frontend"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "bgapp-data"
database_id = "46ed7435-1b25-498d-b832-7bef98061df3"

[env.production]
name = "bgapp-frontend"

[env.production.vars]
NODE_ENV = "production"
DOMAIN = "bgapp-frontend.pages.dev"